CreateBasicEndpoint
klezner/project2-sages pull request #1
Opened 2022-05-18 16:34 UTC by M1C3E4

2022-05-18 16:38 UTC, klezner requested changes

2022-05-18 16:38 UTC, klezner commented on src/main/java/com/sages/project2/HelloWorldREST.java
> +        return "witajSwiecie";
dodaj do stalej

2022-05-19 07:00 UTC, bartmj approved these changes
działa

2022-05-19 08:45 UTC, LukeJaromin approved these changes

2022-05-19 09:08 UTC, LukeJaromin approved these changes

2022-05-19 10:33 UTC, klezner approved these changes
ok

2022-05-19 10:52 UTC, merged