Feature/proj2 5 create basic configuration of ci/cd
klezner/project2-sages pull request #2
Opened 2022-05-18 16:55 UTC by M1C3E4

2022-05-18 17:05 UTC, klezner requested changes

2022-05-18 17:05 UTC, klezner commented on pom.xml
> +                    <target>1.8</target>
17

2022-05-18 17:05 UTC, klezner commented on src/main/java/com/sages/project2/HelloWorldREST.java
> +        String text = "witajSwiecie";
pole w klasie private static final

2022-05-18 17:21 UTC, klezner approved these changes

2022-05-19 08:37 UTC, LukeJaromin approved these changes

2022-05-19 10:54 UTC, merged